name: argocd-demo-cicd
on: 
  push:
    branches: 
      - main
permissions:
  contents: write
jobs:
  ci-cd:
    name: "App CI execution"
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: jlinares14/argocd-demo:${{ github.sha }}

      - name: Update Image tag - Dev
        run: |
          ls -al
          sed "s/IMG_FULL_PATH_PLACEHOLDER/jlinares14\/argocd-demo/g" helm/values/values-dev-template.yaml > helm/values-dev.yaml
          sed -i "s/TAG_PLACEHOLDER/${{ github.sha }}/g" helm/values-dev.yaml
          ls -al
          cat helm/values-dev.yaml

      - name: Diff
        run: git diff

      - name: Add and commit
        run: |
          git config --global user.name 'Arthic-Cero'
          git config --global user.email '${{ secrets.USER_EMAIL }}'
          git add helm/values-dev.yaml
          git commit -m "Updating image tag to jlinares14/argocd-demo:${{ github.sha }} in helm dev values file"

      - name: Push
        run: git push
          
          
