name: argocd-demo-ci
on: 
  push:
    branches-ignore: 
      - main
jobs:
  ci:
    name: "App CI execution"
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: jlinares14/argocd-demo:${{ github.sha }}
        
